-- Проверить подтипы для ДПВ
SELECT PST.P_G_PAY_OUT_SUB_TYPE, 
       PST.NAME_RU,
       PST.P_G_PAY_OUT_TYPE,
       PST.IS_PART,
       PT.NAME_RU AS TYPE_NAME
FROM P_G_PAY_OUT_SUB_TYPE PST
JOIN P_G_PAY_OUT_TYPE PT ON PT.P_G_PAY_OUT_TYPE = PST.P_G_PAY_OUT_TYPE
WHERE PST.NAME_RU LIKE '%ДПВ%'
   OR PST.NAME_RU LIKE '%добровол%'
ORDER BY PST.P_G_PAY_OUT_SUB_TYPE;

-- Проверить существующие выплаты по договорам
SELECT PC.P_G_CONTRACT_KND,
       CK.NAME_RU AS CONTRACT_TYPE,
       PST.P_G_PAY_OUT_SUB_TYPE,
       PST.NAME_RU AS SUBTYPE_NAME,
       COUNT(*) CNT
FROM P_CLAIM_PAY_OUT CPO
JOIN P_CONTRACT PC ON PC.P_CONTRACT = CPO.P_CONTRACT
JOIN P_G_CONTRACT_KND CK ON CK.P_G_CONTRACT_KND = PC.P_G_CONTRACT_KND
JOIN P_G_PAY_OUT_SUB_TYPE PST ON PST.P_G_PAY_OUT_SUB_TYPE = CPO.P_G_PAY_OUT_SUB_TYPE
WHERE PC.P_G_CONTRACT_KND IN (1, 10, 11, 18)
  AND CPO.DATE_REGISTR >= ADD_MONTHS(SYSDATE, -3)
GROUP BY PC.P_G_CONTRACT_KND, CK.NAME_RU, PST.P_G_PAY_OUT_SUB_TYPE, PST.NAME_RU
ORDER BY PC.P_G_CONTRACT_KND, PST.P_G_PAY_OUT_SUB_TYPE;
